data: !include config/grype-db-manager/include.d/data.yaml

grype-db: !include config/grype-db-manager/include.d/grype-db-local-build.yaml

distribution: !include config/grype-db-manager/include.d/distribution-production.yaml

validate: !include config/grype-db-manager/include.d/validate.yaml
