# this configuration is intended to be used for nightly builds of the database in production

data: !include config/grype-db-manager/include.d/data.yaml

grype-db: !include config/grype-db-manager/include.d/grype-db-local-build.yaml

distribution: !include config/grype-db-manager/include.d/distribution-production-r2.yaml

validate: !include config/grype-db-manager/include.d/validate.yaml

assert-aws-credentials: false