# note: this file is not intended to be used for the daily-db-sync workflow to populate a vulnerability data cache

provider:
  root: data/vunnel

  # No manual configs are provided since 'provider.vunnel.generateConfigs' is set to true
  # this means that well run vunnel to get the list of supported providers. All supported providers
  # will be included in the database build. This prevents the need from manually updating this file
  # for every new provider that is added.
  #
  # Any providers that should be excluded from processing should be added to the 'provider.vunnel.excludeProviders' list.
  configs: []

  vunnel:
    executor: docker
    docker-tag: latest
    generate-configs: true
    env:
      GITHUB_TOKEN: $GITHUB_TOKEN
      NVD_API_KEY: $NVD_API_KEY

pull:
  parallelism: 4

package:
  publish-base-url: https://toolbox-data.anchore.io/grype/databases
