# this is a grype-db application configuration file intended for use with the daily db publisher workflow

provider:
  root: data/vunnel

  # No manual configs are provided since 'provider.vunnel.generateConfigs' is set to true
  # this means that well run vunnel to get the list of supported providers. All supported providers
  # will be included in the database build. This prevents the need from manually updating this file
  # for every new provider that is added.
  #
  # Any providers that should be excluded from processing should be added to the 'provider.vunnel.excludeProviders' list.
  configs:
    - name: nvd
    - name: alpine
    - name: alma
    - name: arch
    - name: amazon
    - name: bitnami
    - name: chainguard
    - name: chainguard-libraries
    - name: debian
    - name: echo
    - name: eol
    - name: epss
    - name: fedora
    - name: github
    - name: kev
    - name: mariner
    - name: minimos
    - name: oracle
    - name: photon
    - name: rhel
    - name: secureos
    - name: sles
    - name: ubuntu
    - name: wolfi

  vunnel:
    executor: docker
    docker-tag: latest
    generate-configs: false
    env:
      GITHUB_TOKEN: $GITHUB_TOKEN
      NVD_API_KEY: $NVD_API_KEY

build:
  batch-size: 10000

pull:
  parallelism: 4

package:
  # required for v5
  publish-base-url: https://grype.anchore.io/databases
